USE PEDIDOS;

SELECT TOP 10
	DESCRICAO,CONVERT(DECIMAL(10,2),(PRECO_VENDA - PRECO_CUSTO)) AS LUCRO_UNIT,
	CEILING((((PRECO_VENDA - PRECO_CUSTO)-1)*100))
	AS PERC_LUCRO FROM TB_PRODUTO ORDER BY (PRECO_VENDA-PRECO_CUSTO) ASC
--------- PARTE 2 ------------

SELECT 
	NOME,CONVERT(VARCHAR(10),DATA_NASCIMENTO,103) AS COLUNA_NOVA_DATA_DE_QUARTA,
	DATEDIFF(YEAR,DATA_NASCIMENTO,'2020/04/17') AS IDADE_ANOS


FROM TB_EMPREGADO WHERE DATA_NASCIMENTO > '1951' AND DATEPART(WEEKDAY,DATA_NASCIMENTO) = 4
--------- PARTE 3 -------------------

SELECT *,  
	SITUACAO = 'C'
FROM TB_PEDIDO WHERE (DATA_EMISSAO BETWEEN '2017-01-01' and '2017-04-31' or DATA_EMISSAO between '2018-05-01' and '2018-08-20')
--Professor tentei de todas as formas nenhuma funcionou, ou retorna vazia ou da erro 



SELECT *
FROM TB_PEDIDO


----- PARTE 4 ---

SELECT
	*,
	LOWER (REPLACE (NOME, ' ', '_')) + '@impacta.com.br' AS EMAIL,
	CASE 
	WHEN DATA_CAD IS NULL THEN 'Nao possui' 
	ELSE 'possui'
	END DATA_CAD 
From TB_VENDEDOR

SELECT * FROM TB_VENDEDOR