CREATE TABLE USUARIO 
(
	ID_USUARIO INT IDENTITY (1,1) NOT NULL,
	LOGIN_USUARIO VARCHAR(30) NOT NULL,
	SENHA_USUATIO VARCHAR(25) NOT NULL,
	DTEXPIRACAO VARCHAR NOT NULL
);

CREATE TABLE COORDENADOR (
	ID_USUARIO_COORDENADOR INT IDENTITY (1,1) NOT NULL,
	ID_COORDENADOR INT NOT NULL,
	NOME_COD CHAR (20) NOT NULL,
	EMAIL_COD VARCHAR(40)NOT NULL,
	CELULAR_COD VARCHAR (10)NOT NULL
);

CREATE TABLE PROFESSOR (
	ID_USUARIO_PROFESSOR INT IDENTITY (1,1) NOT NULL,
	ID_PROFESSOR INT NOT NULL,
	NOME_PROF CHAR (20) NOT NULL,
	EMAIL_PROF VARCHAR (20) NOT NULL,
	CELULAR VARCHAR (10), 
	APELIDO VARCHAR (15)
);

CREATE TABLE ALUNO (
	ID_USUARIO_ALUNO IDENTITY (1,1) NOT NULL,
	ID_ALUNO INT NOT NULL,
	ALUNO_NOME CHAR (20) NOT NULL,
	ALUNO_EMAIL VARCHAR(20) NOT NULL,
	ALUNO_CELULAR VARCHAR(10),
	ALUNO_RA INT
	--FOTO
);

ALTER TABLE USUARIO ADD
	CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID_USUARIO);

ALTER TABLE COORDENADOR ADD
		CONSTRAINT PK_ID_COORDERDADOR PRIMARY KEY (ID_COORDENADOR),
		CONSTRAINT FK_ID_USUARIO_COORDENADOR FOREIGN KEY (ID_USUARIO_COORDENADOR)
		REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE PROFESSOR ADD
	CONSTRAINT PK_ID_PROFESSOR PRIMARY KEY (ID_PROFESSOR),
		CONSTRAINT FK_ID_USUARIO_PROFESSOR FOREIGN KEY (ID_USUARIO_PROFESSOR)
		REFERENCES USUARIO (ID_USUARIO);

ALTER TABLE ALUNO ADD
		CONSTRAINT PK_ID_ALUNO PRIMARY KEY (ID_ALUNO),
		CONSTRAINT FK_ID_USUARIO_ALUNO FOREIGN KEY (ID_USUARIO_ALUNO)
		REFERENCES USUARIO (ID_USUARIO);


INSERT INTO USUARIO (LOGIN_USUARIO,SENHA_USUATIO,DTEXPIRACAO)
VALUES ('OO', 'V23V69', '0');

INSERT INTO COORDENADOR(NOME_COD,CELULAR_COD,EMAIL_COD,ID_COORDENADOR,ID_USUARIO_COORDENADOR)
VALUES ('ANTONIO','979532484','vso1997@gmail.com',1,1)




DROP TABLE USUARIO
DROP TABLE COORDENADOR


SELECT * FROM USUARIO

SELECT * FROM COORDENADOR
